version: "3"
services:
  postgresql:
    image: postgres:15.4
    container_name: postgres_new
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgresql_bd_net

#  backend:
#    container_name: backend
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#    environment:
#      POSTGRES_SERVER: postgresql
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: blps
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#    networks:
#      - postgresql_bd_net

networks:
  postgresql_bd_net:
    driver: bridge

volumes:
  postgresql-data: